services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: wasel_palestine
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/wasel_palestine
      PORT: "3000"
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ORS_API_KEY: ${ORS_API_KEY}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node src/db/seed.js && node index.js"

volumes:
  pgdata:
